### ISSUE TITLE
GDPR local storage

### ISSUE THREAD

**Issue by He3556** [creame/joinchat#12]
Hello i have the free version, where the feature (show button after x page visits) is not present. 
But when i check my **local storage** the plugin is counting page visits. 

The problem is that this is not allowed in EU and it is possible that people have to pay high fines because of this. 
I really wish that international developers would care more about this facts.

I could try and argue that it (local storage) is technical necessary - but in this case it isn't, because i can't use that feature anyway, in the free version.

So this should really be deactivated by default in the free version.

**Any other idea how i can switch it off?**

thanks!

**Comment by pacotole** [comment]
Hi, this function is used in the free version.

When a "Call to Action" is defined you can have the chat window with that CTA appear automatically on the first visit or after "n" visits. That is the function of the accountant.

The data can be considered technically necessary to improve the user experience, is first party (does not inform third parties) and does not store any personal data.

Anyway, you are right that if there is no CTA or the chat window is shown on the first visit there is no reason to save the data and we can avoid it.

We will try to correct that in the next versions.

**Comment by pacotole** [comment]
In joinchat 5.1 this has already been fixed.

Cookies are only saved when necessary and the Joinchat settings warn you when the configuration needs to use them.
